{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 80,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.models import load_model\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from keras.callbacks import EarlyStopping\n",
    "\n",
    "# Load the model\n",
    "# model = load_model(\"plastic_classifier_model.keras\")\n",
    "model = load_model(\"8_point_plastic_classifier_model.keras\")\n",
    "\n",
    "data = pd.read_csv(\"Alltogether2.4v.csv\")\n",
    "# data = pd.read_csv(\"modified_data.csv\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "in user code:\n\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2341, in predict_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2327, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2315, in run_step  **\n        outputs = model.predict_step(data)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2283, in predict_step\n        return self(x, training=False)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_47\" is incompatible with the layer: expected shape=(None, 8), found shape=(None, 15)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[82], line 17\u001b[0m\n\u001b[0;32m     14\u001b[0m X_test_normalized \u001b[39m=\u001b[39m ((X_test \u001b[39m-\u001b[39m \u001b[39m0\u001b[39m) \u001b[39m/\u001b[39m (\u001b[39m8410000\u001b[39m \u001b[39m-\u001b[39m \u001b[39m0\u001b[39m))\n\u001b[0;32m     16\u001b[0m \u001b[39m# Make predictions\u001b[39;00m\n\u001b[1;32m---> 17\u001b[0m predictions \u001b[39m=\u001b[39m model\u001b[39m.\u001b[39;49mpredict(X_test_normalized)\n\u001b[0;32m     18\u001b[0m predicted_labels \u001b[39m=\u001b[39m np\u001b[39m.\u001b[39margmax(predictions, axis\u001b[39m=\u001b[39m\u001b[39m1\u001b[39m)\n\u001b[0;32m     19\u001b[0m predicted_plastic_types \u001b[39m=\u001b[39m label_encoder\u001b[39m.\u001b[39minverse_transform(predicted_labels)\n",
      "File \u001b[1;32mc:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32m~\\AppData\\Local\\Temp\\__autograph_generated_file9y6tx26z.py:15\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__predict_function\u001b[1;34m(iterator)\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     14\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m---> 15\u001b[0m     retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(step_function), (ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m), ag__\u001b[39m.\u001b[39mld(iterator)), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[0;32m     16\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m     17\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "\u001b[1;31mValueError\u001b[0m: in user code:\n\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2341, in predict_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2327, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2315, in run_step  **\n        outputs = model.predict_step(data)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2283, in predict_step\n        return self(x, training=False)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_47\" is incompatible with the layer: expected shape=(None, 8), found shape=(None, 15)\n"
     ]
    }
   ],
   "source": [
    "# Separate features and labels\n",
    "X = data.drop(columns=[\"Material_Type\"])\n",
    "y = data[\"Material_Type\"]\n",
    "\n",
    "# Encode labels\n",
    "label_encoder = LabelEncoder()\n",
    "y_encoded = label_encoder.fit_transform(y)\n",
    "\n",
    "# Split the data into train and test sets (Normal)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)\n",
    "\n",
    "\n",
    "# Normalize the manual input if needed\n",
    "X_test_normalized = ((X_test - 0) / (8410000 - 0))\n",
    "\n",
    "# Make predictions\n",
    "predictions = model.predict(X_test_normalized)\n",
    "predicted_labels = np.argmax(predictions, axis=1)\n",
    "predicted_plastic_types = label_encoder.inverse_transform(predicted_labels)\n",
    "\n",
    "# Evaluate the model\n",
    "test_loss, test_accuracy = model.evaluate(X_test_normalized, y_test)\n",
    "\n",
    "# Make predictions\n",
    "predictions = model.predict(X_test_normalized)\n",
    "\n",
    "# Get the top 4 predictions for each sample\n",
    "top_predictions = np.argsort(predictions, axis=1)[:, -4:]\n",
    "top_labels = top_predictions[:, ::-1]\n",
    "\n",
    "# print(predictions)\n",
    "\n",
    "# Reshape the top_labels array to be 1D\n",
    "top_labels_1d = top_labels.reshape(-1)\n",
    "\n",
    "# Inverse transform the labels\n",
    "top_plastic_types = label_encoder.inverse_transform(top_labels_1d)\n",
    "\n",
    "# Reshape the top_plastic_types array back to 2D\n",
    "top_plastic_types = top_plastic_types.reshape(top_labels.shape)\n",
    "\n",
    "# Get the percentage likelihoods for the top 4 predictions\n",
    "percentage_likelihoods = np.take_along_axis(predictions, top_predictions, axis=1) * 100\n",
    "\n",
    "# Display test accuracy and example predictions\n",
    "print(f\"Test Accuracy: {test_accuracy}\")\n",
    "for i in range(len(predicted_labels)):\n",
    "    num_predictions = min(4, len(np.unique(top_labels[i])))\n",
    "    if y_test[i] == predicted_labels[i]:\n",
    "        CorF = \"Correct,\"\n",
    "    else:\n",
    "        CorF = \"False,\"\n",
    "    print(f\"Sample {i+1}: {CorF} it was {label_encoder.classes_[y_test[i]]}\")\n",
    "    for j in range(num_predictions):\n",
    "        print(f\"  Prediction {j+1}: {top_plastic_types[i][j]} with {percentage_likelihoods[i][3-j]:.2f}% likelihood\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "in user code:\n\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2341, in predict_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2327, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2315, in run_step  **\n        outputs = model.predict_step(data)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2283, in predict_step\n        return self(x, training=False)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_47\" is incompatible with the layer: expected shape=(None, 8), found shape=(None, 15)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[83], line 11\u001b[0m\n\u001b[0;32m      8\u001b[0m X_test_normalized \u001b[39m=\u001b[39m ((X_test \u001b[39m-\u001b[39m \u001b[39m0\u001b[39m) \u001b[39m/\u001b[39m (\u001b[39m8410000\u001b[39m \u001b[39m-\u001b[39m \u001b[39m0\u001b[39m))\n\u001b[0;32m     10\u001b[0m \u001b[39m# Make predictions\u001b[39;00m\n\u001b[1;32m---> 11\u001b[0m predictions \u001b[39m=\u001b[39m model\u001b[39m.\u001b[39;49mpredict(X_test_normalized)\n\u001b[0;32m     12\u001b[0m predicted_labels \u001b[39m=\u001b[39m np\u001b[39m.\u001b[39margmax(predictions, axis\u001b[39m=\u001b[39m\u001b[39m1\u001b[39m)\n\u001b[0;32m     13\u001b[0m predicted_plastic_types \u001b[39m=\u001b[39m label_encoder\u001b[39m.\u001b[39minverse_transform(predicted_labels)\n",
      "File \u001b[1;32mc:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32m~\\AppData\\Local\\Temp\\__autograph_generated_file9y6tx26z.py:15\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__predict_function\u001b[1;34m(iterator)\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     14\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m---> 15\u001b[0m     retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(step_function), (ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m), ag__\u001b[39m.\u001b[39mld(iterator)), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[0;32m     16\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m     17\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "\u001b[1;31mValueError\u001b[0m: in user code:\n\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2341, in predict_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2327, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2315, in run_step  **\n        outputs = model.predict_step(data)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2283, in predict_step\n        return self(x, training=False)\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"c:\\Users\\kylej\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_47\" is incompatible with the layer: expected shape=(None, 8), found shape=(None, 15)\n"
     ]
    }
   ],
   "source": [
    "# Filter data to exclude 'ALU'\n",
    "exclude_alu_indices = y != 'ALU'\n",
    "X_filtered = X[exclude_alu_indices]\n",
    "y_filtered = y_encoded[exclude_alu_indices]\n",
    "# Split the filtered data into train and test sets (Filtered ALU)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_filtered, y_filtered, test_size=0.2, random_state=50)\n",
    "#features\n",
    "X_test_normalized = ((X_test - 0) / (8410000 - 0))\n",
    "\n",
    "# Make predictions\n",
    "predictions = model.predict(X_test_normalized)\n",
    "predicted_labels = np.argmax(predictions, axis=1)\n",
    "predicted_plastic_types = label_encoder.inverse_transform(predicted_labels)\n",
    "\n",
    "# Evaluate the model\n",
    "test_loss, test_accuracy = model.evaluate(X_test_normalized, y_test)\n",
    "\n",
    "# Make predictions\n",
    "predictions = model.predict(X_test_normalized)\n",
    "\n",
    "# Get the top 4 predictions for each sample\n",
    "top_predictions = np.argsort(predictions, axis=1)[:, -4:]\n",
    "top_labels = top_predictions[:, ::-1]\n",
    "\n",
    "# print(predictions)\n",
    "\n",
    "# Reshape the top_labels array to be 1D\n",
    "top_labels_1d = top_labels.reshape(-1)\n",
    "\n",
    "# Inverse transform the labels\n",
    "top_plastic_types = label_encoder.inverse_transform(top_labels_1d)\n",
    "\n",
    "# Reshape the top_plastic_types array back to 2D\n",
    "top_plastic_types = top_plastic_types.reshape(top_labels.shape)\n",
    "\n",
    "# Get the percentage likelihoods for the top 4 predictions\n",
    "percentage_likelihoods = np.take_along_axis(predictions, top_predictions, axis=1) * 100\n",
    "\n",
    "# Display test accuracy and example predictions\n",
    "print(f\"Test Accuracy: {test_accuracy}\")\n",
    "for i in range(len(predicted_labels)):\n",
    "    num_predictions = min(4, len(np.unique(top_labels[i])))\n",
    "    if y_test[i] == predicted_labels[i]:\n",
    "        CorF = \"Correct,\"\n",
    "    else:\n",
    "        CorF = \"False,\"\n",
    "    print(f\"Sample {i+1}: {CorF} it was {label_encoder.classes_[y_test[i]]}\")\n",
    "    for j in range(num_predictions):\n",
    "        print(f\"  Prediction {j+1}: {top_plastic_types[i][j]} with {percentage_likelihoods[i][3-j]:.2f}% likelihood\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# # Get manual input from the user\n",
    "# manual_input = np.array([[1131269, 2601405, 4068371, 4607823, 6112788, 3924625, 2537470, 1568820, 1381303, 2712828, 3808213, 5044933, 4784589, 3128572, 2013441]])  # Replace with your input values\n",
    "\n",
    "# # Normalize the manual input if needed\n",
    "# normalized_manual_input = ((manual_input - 0) / (8410000 - 0))\n",
    "\n",
    "# # Make predictions on manual input\n",
    "# predictions = model.predict(normalized_manual_input)\n",
    "# print(predictions)\n",
    "\n",
    "# # Get the top prediction\n",
    "# top_prediction = np.argmax(predictions)\n",
    "# print(top_prediction)\n",
    "\n",
    "# top_plastic_type = label_encoder.inverse_transform([top_prediction])[0]\n",
    "# print(top_plastic_type)\n",
    "# likelihood = predictions[0][top_prediction] * 100\n",
    "\n",
    "# # Display the prediction for manual input\n",
    "# print(f\"Manual Input Prediction:\")\n",
    "# print(f\"  Prediction: {top_plastic_type} with {likelihood:.2f}% likelihood\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import pandas as pd\n",
    "# import numpy as np\n",
    "\n",
    "# # Read the CSV file\n",
    "# original_data = pd.read_csv(\"original_data.csv\")\n",
    "\n",
    "# # Exclude the first row and 'P' column\n",
    "# data_to_modify = original_data.iloc[1:, 0:]  # Exclude first row and first column\n",
    "# p_column = original_data.iloc[1:, 15]       # Assuming 'P' is at index 15\n",
    "\n",
    "# # Apply random changes\n",
    "# percentage_change_range = 0.05  # 5%\n",
    "# numeric_data_to_modify = data_to_modify.apply(pd.to_numeric, errors='coerce')\n",
    "# random_changes = np.random.uniform(-percentage_change_range, percentage_change_range, size=numeric_data_to_modify.shape)\n",
    "# modified_data = numeric_data_to_modify + (numeric_data_to_modify * random_changes)\n",
    "\n",
    "\n",
    "# # Combine modified data with the first row and the 'P' column\n",
    "# first_row = original_data.iloc[0]\n",
    "# modified_data_with_row = pd.concat([first_row, modified_data], axis=1)\n",
    "# modified_data_with_row.insert(15, 'P', p_column)  # Insert 'P' column back\n",
    "\n",
    "# # Save the modified data\n",
    "# modified_data_with_row.to_csv(\"modified_data.csv\", index=False)\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
